.TH vdf_get 3

.SH NAME
vdf_get

.SH LIBRARY
Valve Data Format Parser Library (libvdfc)

.SH SYNOPSIS
#include <vdfc/vdf.h>

VDFNode *vdf_get(const VDFNode *object, const char *key);

.SH DESCRIPTION
Look up a direct child of `object` by key.

.SH RETURN VALUE
Returns the matching child node.
Returns NULL if `object` is not an object (\fB`VDF_VAL_OBJECT`\fR) or if no
child has that key.

.SH ERRORS
None.

.SH SEE ALSO
.BR vdf_read_file (3),
.BR vdf_parse (3),
.BR vdf_get_string (3),
.BR vdf_get_int (3),
.BR vdf_get_bool (3),
.BR vdf_dump_node (3),
.BR vdf_free_node (3),
.BR libvdfc_errors (3)
